### PR TITLE
docs: update links to point to published Discovery Recommendation

### LINKED ISSUE #61: Update documentation link with the published Discovery Specification
In the recently introduced [insert response content type fix](https://github.com/vaimee/zion/blob/2ad535d519d251352f96c3871b6427442b0a7fb0/src/introduction/td-builder.service.ts#L48), we added a reference to the current draft of Discovery Specification. When the Discovery spec reaches the Recommendation phase we should update that link. 

Tracking TODO: https://github.com/vaimee/zion/blob/2ad535d519d251352f96c3871b6427442b0a7fb0/src/introduction/td-builder.service.ts#L45

### PR DESCRIPTION
**Pull request by JKRhb**
Should resolve #61.

### CODE REVIEW

**Review by relu91 — CHANGES_REQUESTED** [review]
Thank you @JKRhb as always. I noticed that you pointed to the latest published version. I think it is safer to point to the [versioned document](https://www.w3.org/TR/2023/REC-wot-discovery-20231205/). What do you think?

**Comment by JKRhb** [comment]
> Thank you @JKRhb as always. I noticed that you pointed to the latest published version. I think it is safer to point to the [versioned document](https://www.w3.org/TR/2023/REC-wot-discovery-20231205/). What do you think?

Thank you, @relu91, that was a very good point! The PR should now be updated accordingly :)

**Review by relu91 — APPROVED** [review]
Ok good to go from my side!

**Comment by hyperloris** [comment]
Thank you @JKRhb for the new contribution. I looked at the PR status, and it's also a green light for me.

**Review by hyperloris — APPROVED** [review]

**Pull request merged**
